DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 8
    SAMPLER:
      RandomSampler
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 0

DATASET:
  NAME: SFOffice

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["gaussian_noise", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 200
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 10

TEST:
  FINAL_MODEL: "best_val"

TRAINER:
  PROMPTSTYLER:
    N_STYLE: 80
    EPS: 1e-7
    S: 5.0
    M: 0.5
    CLASS_DIR: "PromptStyler/data/office.txt"
    CHECKPOINT_NAME: "style.pth"
